{"uid":"d2415df7a6ffc157","name":"a1-valves.com заказать звонок -- @1.1 ","fullName":"Проверка сайта a1-valves.com: a1-valves.com заказать звонок","historyId":"7faf572cfcca69d732baa5f93ff54721","time":{"start":1667846550836,"stop":1667846576379,"duration":25543},"status":"broken","statusMessage":"urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=52509): Max retries exceeded with url: /session/7d62b791e5f18b7197021e3ff11da060/screenshot (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x113791570>: Failed to establish a new connection: [Errno 61] Connection refused'))\n","statusTrace":"  File \"/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/behave/runner.py\", line 545, in run_hook\n    self.hooks[name](context, *args)\n  File \"features/environment.py\", line 95, in after_step\n    bot.send_photo(chat_id=-447406725, photo=context.driver.get_screenshot_as_png(),\n  File \"/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/selenium/webdriver/remote/webdriver.py\", line 1357, in get_screenshot_as_png\n    return b64decode(self.get_screenshot_as_base64().encode('ascii'))\n  File \"/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/selenium/webdriver/remote/webdriver.py\", line 1369, in get_screenshot_as_base64\n    return self.execute(Command.SCREENSHOT)['value']\n  File \"/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/selenium/webdriver/remote/webdriver.py\", line 423, in execute\n    response = self.command_executor.execute(driver_command, params)\n  File \"/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/selenium/webdriver/remote/remote_connection.py\", line 333, in execute\n    return self._request(command_info[0], url, body=data)\n  File \"/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/selenium/webdriver/remote/remote_connection.py\", line 355, in _request\n    resp = self._conn.request(method, url, body=body, headers=headers)\n  File \"/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/urllib3/request.py\", line 66, in request\n    return self.request_encode_url(method, url, fields=fields,\n  File \"/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/urllib3/request.py\", line 89, in request_encode_url\n    return self.urlopen(method, url, **extra_kw)\n  File \"/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/urllib3/poolmanager.py\", line 324, in urlopen\n    response = conn.urlopen(method, u.request_uri, **kw)\n  File \"/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/urllib3/connectionpool.py\", line 663, in urlopen\n    return self.urlopen(method, url, body, headers, retries,\n  File \"/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/urllib3/connectionpool.py\", line 663, in urlopen\n    return self.urlopen(method, url, body, headers, retries,\n  File \"/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/urllib3/connectionpool.py\", line 663, in urlopen\n    return self.urlopen(method, url, body, headers, retries,\n  File \"/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/urllib3/connectionpool.py\", line 637, in urlopen\n    retries = retries.increment(method, url, error=e, _pool=self,\n  File \"/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/urllib3/util/retry.py\", line 399, in increment\n    raise MaxRetryError(_pool, url, error or ResponseError(cause))\n","flaky":false,"newFailed":false,"newBroken":false,"newPassed":false,"retriesCount":0,"retriesStatusChange":false,"beforeStages":[],"testStage":{"status":"broken","statusMessage":"urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=52509): Max retries exceeded with url: /session/7d62b791e5f18b7197021e3ff11da060/screenshot (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x113791570>: Failed to establish a new connection: [Errno 61] Connection refused'))\n","statusTrace":"  File \"/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/behave/runner.py\", line 545, in run_hook\n    self.hooks[name](context, *args)\n  File \"features/environment.py\", line 95, in after_step\n    bot.send_photo(chat_id=-447406725, photo=context.driver.get_screenshot_as_png(),\n  File \"/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/selenium/webdriver/remote/webdriver.py\", line 1357, in get_screenshot_as_png\n    return b64decode(self.get_screenshot_as_base64().encode('ascii'))\n  File \"/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/selenium/webdriver/remote/webdriver.py\", line 1369, in get_screenshot_as_base64\n    return self.execute(Command.SCREENSHOT)['value']\n  File \"/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/selenium/webdriver/remote/webdriver.py\", line 423, in execute\n    response = self.command_executor.execute(driver_command, params)\n  File \"/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/selenium/webdriver/remote/remote_connection.py\", line 333, in execute\n    return self._request(command_info[0], url, body=data)\n  File \"/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/selenium/webdriver/remote/remote_connection.py\", line 355, in _request\n    resp = self._conn.request(method, url, body=body, headers=headers)\n  File \"/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/urllib3/request.py\", line 66, in request\n    return self.request_encode_url(method, url, fields=fields,\n  File \"/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/urllib3/request.py\", line 89, in request_encode_url\n    return self.urlopen(method, url, **extra_kw)\n  File \"/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/urllib3/poolmanager.py\", line 324, in urlopen\n    response = conn.urlopen(method, u.request_uri, **kw)\n  File \"/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/urllib3/connectionpool.py\", line 663, in urlopen\n    return self.urlopen(method, url, body, headers, retries,\n  File \"/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/urllib3/connectionpool.py\", line 663, in urlopen\n    return self.urlopen(method, url, body, headers, retries,\n  File \"/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/urllib3/connectionpool.py\", line 663, in urlopen\n    return self.urlopen(method, url, body, headers, retries,\n  File \"/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/urllib3/connectionpool.py\", line 637, in urlopen\n    retries = retries.increment(method, url, error=e, _pool=self,\n  File \"/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/urllib3/util/retry.py\", line 399, in increment\n    raise MaxRetryError(_pool, url, error or ResponseError(cause))\n","steps":[{"name":"Given open a1-valves.com page","time":{"start":1667846550843,"stop":1667846556908,"duration":6065},"status":"passed","steps":[],"attachments":[],"parameters":[],"stepsCount":0,"attachmentsCount":0,"shouldDisplayMessage":false,"hasContent":false},{"name":"When click on order call button in \"top menu section\"","time":{"start":1667846556908,"stop":1667846557465,"duration":557},"status":"passed","steps":[],"attachments":[],"parameters":[],"stepsCount":0,"attachmentsCount":0,"shouldDisplayMessage":false,"hasContent":false},{"name":"When enter \"generated_test_automation_email_call_a1\" in name field in \"request call section\"","time":{"start":1667846557465,"stop":1667846558173,"duration":708},"status":"passed","steps":[],"attachments":[],"parameters":[],"stepsCount":0,"attachmentsCount":0,"shouldDisplayMessage":false,"hasContent":false},{"name":"When enter \"+70000000000\" in phone field in \"request call section\"","time":{"start":1667846558173,"stop":1667846558778,"duration":605},"status":"passed","steps":[],"attachments":[],"parameters":[],"stepsCount":0,"attachmentsCount":0,"shouldDisplayMessage":false,"hasContent":false},{"name":"When click on send button in \"request call section\"","time":{"start":1667846558778,"stop":1667846559342,"duration":564},"status":"passed","steps":[],"attachments":[],"parameters":[],"stepsCount":0,"attachmentsCount":0,"shouldDisplayMessage":false,"hasContent":false},{"name":"Then email with \"generated_test_automation_email_call_a1\" contains \"Телефон : +70000000000\" in 900 sec","time":{"start":1667846559343,"stop":1667846576375,"duration":17032},"status":"broken","statusMessage":"urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=52509): Max retries exceeded with url: /session/7d62b791e5f18b7197021e3ff11da060/screenshot (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x113791570>: Failed to establish a new connection: [Errno 61] Connection refused'))\n","statusTrace":"  File \"/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/behave/runner.py\", line 545, in run_hook\n    self.hooks[name](context, *args)\n  File \"features/environment.py\", line 95, in after_step\n    bot.send_photo(chat_id=-447406725, photo=context.driver.get_screenshot_as_png(),\n  File \"/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/selenium/webdriver/remote/webdriver.py\", line 1357, in get_screenshot_as_png\n    return b64decode(self.get_screenshot_as_base64().encode('ascii'))\n  File \"/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/selenium/webdriver/remote/webdriver.py\", line 1369, in get_screenshot_as_base64\n    return self.execute(Command.SCREENSHOT)['value']\n  File \"/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/selenium/webdriver/remote/webdriver.py\", line 423, in execute\n    response = self.command_executor.execute(driver_command, params)\n  File \"/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/selenium/webdriver/remote/remote_connection.py\", line 333, in execute\n    return self._request(command_info[0], url, body=data)\n  File \"/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/selenium/webdriver/remote/remote_connection.py\", line 355, in _request\n    resp = self._conn.request(method, url, body=body, headers=headers)\n  File \"/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/urllib3/request.py\", line 66, in request\n    return self.request_encode_url(method, url, fields=fields,\n  File \"/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/urllib3/request.py\", line 89, in request_encode_url\n    return self.urlopen(method, url, **extra_kw)\n  File \"/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/urllib3/poolmanager.py\", line 324, in urlopen\n    response = conn.urlopen(method, u.request_uri, **kw)\n  File \"/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/urllib3/connectionpool.py\", line 663, in urlopen\n    return self.urlopen(method, url, body, headers, retries,\n  File \"/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/urllib3/connectionpool.py\", line 663, in urlopen\n    return self.urlopen(method, url, body, headers, retries,\n  File \"/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/urllib3/connectionpool.py\", line 663, in urlopen\n    return self.urlopen(method, url, body, headers, retries,\n  File \"/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/urllib3/connectionpool.py\", line 637, in urlopen\n    retries = retries.increment(method, url, error=e, _pool=self,\n  File \"/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/urllib3/util/retry.py\", line 399, in increment\n    raise MaxRetryError(_pool, url, error or ResponseError(cause))\n","steps":[],"attachments":[],"parameters":[],"stepsCount":0,"attachmentsCount":0,"shouldDisplayMessage":true,"hasContent":true},{"name":"Given open a1-valves.com page","time":{"start":1667846576379,"stop":1667846576379,"duration":0},"status":"passed","steps":[],"attachments":[],"parameters":[],"stepsCount":0,"attachmentsCount":0,"shouldDisplayMessage":false,"hasContent":false},{"name":"When click on order call button in \"top menu section\"","time":{"start":1667846576379,"stop":1667846576379,"duration":0},"status":"passed","steps":[],"attachments":[],"parameters":[],"stepsCount":0,"attachmentsCount":0,"shouldDisplayMessage":false,"hasContent":false},{"name":"When enter \"generated_test_automation_email_call_a1\" in name field in \"request call section\"","time":{"start":1667846576379,"stop":1667846576379,"duration":0},"status":"passed","steps":[],"attachments":[],"parameters":[],"stepsCount":0,"attachmentsCount":0,"shouldDisplayMessage":false,"hasContent":false},{"name":"When enter \"+70000000000\" in phone field in \"request call section\"","time":{"start":1667846576379,"stop":1667846576379,"duration":0},"status":"passed","steps":[],"attachments":[],"parameters":[],"stepsCount":0,"attachmentsCount":0,"shouldDisplayMessage":false,"hasContent":false},{"name":"When click on send button in \"request call section\"","time":{"start":1667846576379,"stop":1667846576379,"duration":0},"status":"passed","steps":[],"attachments":[],"parameters":[],"stepsCount":0,"attachmentsCount":0,"shouldDisplayMessage":false,"hasContent":false},{"name":"Then email with \"generated_test_automation_email_call_a1\" contains \"Телефон : +70000000000\" in 900 sec","time":{"start":1667846576379,"stop":1667846576379,"duration":0},"status":"broken","statusMessage":"urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=52509): Max retries exceeded with url: /session/7d62b791e5f18b7197021e3ff11da060/screenshot (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x113791570>: Failed to establish a new connection: [Errno 61] Connection refused'))\n","statusTrace":"  File \"/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/behave/runner.py\", line 545, in run_hook\n    self.hooks[name](context, *args)\n  File \"features/environment.py\", line 95, in after_step\n    bot.send_photo(chat_id=-447406725, photo=context.driver.get_screenshot_as_png(),\n  File \"/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/selenium/webdriver/remote/webdriver.py\", line 1357, in get_screenshot_as_png\n    return b64decode(self.get_screenshot_as_base64().encode('ascii'))\n  File \"/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/selenium/webdriver/remote/webdriver.py\", line 1369, in get_screenshot_as_base64\n    return self.execute(Command.SCREENSHOT)['value']\n  File \"/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/selenium/webdriver/remote/webdriver.py\", line 423, in execute\n    response = self.command_executor.execute(driver_command, params)\n  File \"/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/selenium/webdriver/remote/remote_connection.py\", line 333, in execute\n    return self._request(command_info[0], url, body=data)\n  File \"/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/selenium/webdriver/remote/remote_connection.py\", line 355, in _request\n    resp = self._conn.request(method, url, body=body, headers=headers)\n  File \"/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/urllib3/request.py\", line 66, in request\n    return self.request_encode_url(method, url, fields=fields,\n  File \"/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/urllib3/request.py\", line 89, in request_encode_url\n    return self.urlopen(method, url, **extra_kw)\n  File \"/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/urllib3/poolmanager.py\", line 324, in urlopen\n    response = conn.urlopen(method, u.request_uri, **kw)\n  File \"/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/urllib3/connectionpool.py\", line 663, in urlopen\n    return self.urlopen(method, url, body, headers, retries,\n  File \"/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/urllib3/connectionpool.py\", line 663, in urlopen\n    return self.urlopen(method, url, body, headers, retries,\n  File \"/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/urllib3/connectionpool.py\", line 663, in urlopen\n    return self.urlopen(method, url, body, headers, retries,\n  File \"/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/urllib3/connectionpool.py\", line 637, in urlopen\n    retries = retries.increment(method, url, error=e, _pool=self,\n  File \"/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/urllib3/util/retry.py\", line 399, in increment\n    raise MaxRetryError(_pool, url, error or ResponseError(cause))\n","steps":[],"attachments":[],"parameters":[],"stepsCount":0,"attachmentsCount":0,"shouldDisplayMessage":true,"hasContent":true}],"attachments":[],"parameters":[],"stepsCount":12,"attachmentsCount":0,"shouldDisplayMessage":false,"hasContent":true},"afterStages":[],"labels":[{"name":"severity","value":"normal"},{"name":"tag","value":"regression"},{"name":"feature","value":"Проверка сайта a1-valves.com"},{"name":"framework","value":"behave"},{"name":"language","value":"cpython3"},{"name":"resultFormat","value":"allure2"}],"parameters":[{"name":"section","value":"top menu section"}],"links":[],"hidden":false,"retry":false,"extra":{"severity":"normal","retries":[],"categories":[{"name":"Test defects","matchedStatuses":[],"flaky":false}],"history":{"statistic":{"failed":0,"broken":4,"skipped":0,"passed":8,"unknown":0,"total":12},"items":[{"uid":"c90f5a02ca0bc79c","reportUrl":"https://automation-emk.github.io/popup-automation/35//#testresult/c90f5a02ca0bc79c","status":"broken","statusDetails":"urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=52509): Max retries exceeded with url: /session/7d62b791e5f18b7197021e3ff11da060/screenshot (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x113791570>: Failed to establish a new connection: [Errno 61] Connection refused'))\n","time":{"start":1667846550836,"stop":1667846576379,"duration":25543}},{"uid":"84272e5b25a62b73","reportUrl":"https://automation-emk.github.io/popup-automation/34//#testresult/84272e5b25a62b73","status":"broken","statusDetails":"urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=52509): Max retries exceeded with url: /session/7d62b791e5f18b7197021e3ff11da060/screenshot (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x113791570>: Failed to establish a new connection: [Errno 61] Connection refused'))\n","time":{"start":1667846550836,"stop":1667846576379,"duration":25543}},{"uid":"11d6fb4044521f88","reportUrl":"https://automation-emk.github.io/popup-automation/33//#testresult/11d6fb4044521f88","status":"broken","statusDetails":"urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=52509): Max retries exceeded with url: /session/7d62b791e5f18b7197021e3ff11da060/screenshot (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x113791570>: Failed to establish a new connection: [Errno 61] Connection refused'))\n","time":{"start":1667846550836,"stop":1667846576379,"duration":25543}},{"uid":"af0029d221502abf","reportUrl":"https://automation-emk.github.io/popup-automation/32//#testresult/af0029d221502abf","status":"passed","time":{"start":1669838434396,"stop":1669838537410,"duration":103014}},{"uid":"4b88326c32a639b5","reportUrl":"https://automation-emk.github.io/popup-automation/31//#testresult/4b88326c32a639b5","status":"passed","time":{"start":1669778091551,"stop":1669778104708,"duration":13157}},{"uid":"2183efc74fd682c2","reportUrl":"https://automation-emk.github.io/popup-automation/30//#testresult/2183efc74fd682c2","status":"passed","time":{"start":1669691859743,"stop":1669691870954,"duration":11211}},{"uid":"5c647fe798a54389","reportUrl":"https://automation-emk.github.io/popup-automation/29//#testresult/5c647fe798a54389","status":"passed","time":{"start":1669605662151,"stop":1669605674792,"duration":12641}},{"uid":"2cf505ff1dc14094","reportUrl":"https://automation-emk.github.io/popup-automation/28//#testresult/2cf505ff1dc14094","status":"passed","time":{"start":1669520700706,"stop":1669520715579,"duration":14873}},{"uid":"b40ecdace85d5b64","reportUrl":"https://automation-emk.github.io/popup-automation/27//#testresult/b40ecdace85d5b64","status":"passed","time":{"start":1669432380818,"stop":1669432391577,"duration":10759}},{"uid":"15fde6d49d25ae94","reportUrl":"https://automation-emk.github.io/popup-automation/26//#testresult/15fde6d49d25ae94","status":"passed","time":{"start":1669347682830,"stop":1669347695436,"duration":12606}},{"uid":"3aa2c15abedef6fd","reportUrl":"https://automation-emk.github.io/popup-automation/25//#testresult/3aa2c15abedef6fd","status":"passed","time":{"start":1669284215473,"stop":1669284329573,"duration":114100}}]},"tags":["regression"]},"source":"d2415df7a6ffc157.json","parameterValues":["top menu section"]}